version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql  # Initialize DB
    networks:
      - fastapi-network
    ports:
      - "5432:5432"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "fluentd:24224"
        tag: "docker.db"

  app:
    build: ./app
    volumes:
      - ./app:/app
    depends_on:
      - db
      - fluentd
    environment:
      - DATABASE_URL=postgresql+psycopg2://user:password@db:5432/mydb
      - PYTHONPATH=/app
    networks:
      - fastapi-network
    ports:
      - "8000:8000"
    logging:
      driver: "fluentd"
      options:
        fluentd-address: "fluentd:24224"
        tag: "docker.app"

  fluentd:
    image: fluent/fluentd:v1.18-debian-1
    environment:
      - FLUENTD_CONF=fluent.conf
    volumes:
      - ./fluentd/conf:/fluentd/etc
    networks:
      - fastapi-network
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:24224" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  pgdata:

networks:
  fastapi-network:
    driver: bridge
